name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore StaffMgtAPI.sln

      - name: Build
        run: dotnet build StaffMgtAPI.sln --no-restore
  
      - name: Run tests
        run: dotnet test ../StaffMgtApiUnitTest/StaffMgtApiUnitTest.csproj --no-build --verbosity normal
  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Ensure this matches your .NET Core version
          
      - name: Publish
        run: dotnet publish StaffMgtAPI.csproj -c Release -o publish_output

 #     - name: Deploy to Azure Web App
 #       uses: azure/webapps-deploy@v2
 #      with:
 #         app-name: 'YourWebAppName'  # Update with your Azure Web App name
 #          publish-profile: ${{ secrets.AzureWebAppPublishProfile }}  # Set this secret in your GitHub repository
 #         package: publish_output
